### ISSUE TITLE
`vint32mf2_t` and some other types seems violate the constraint `LMUL ≥ SEW/ELEN` when `ELEN` = 32

### ISSUE THREAD

**Issue by QuarticCat** [riscv-non-isa/rvv-intrinsic-doc#113]
Is this intentional or did I get something wrong?

This constraint may come from the requirement in the spec that [VLEN >= ELEN](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#2-implementation-defined-constant-parameters).

**Comment by topperc** [comment]
You are correct. The compiler will need to disable the intrinsics that use those types when ELEN=32. We can't just remove the types from the spec just because ELEN might be 32. They are needed to support some widening/narrowing conversions for ELEN>=64. So it needs to be determined at compile time if the types exist.

**Comment by QuarticCat** [comment]
So the table below needs some modifications?

https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#data-types

**Comment by topperc** [comment]
Yes https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/114
